### PR TITLE
Name tarball following release-version convention

### PR DESCRIPTION
**Pull request by deniseyu**
Addresses https://github.com/concourse/bosh-io-release-resource/issues/10

https://www.pivotaltracker.com/story/show/91865930

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@deniseyu Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/bosh-io-release-resource&pullRequestId=11)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/bosh-io-release-resource&pullRequestId=11) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by deniseyu** [comment]
Hey folks, I've signed the CLA but I'm a Pivotal employee. Anything else I need to do?

**Comment by pivotal-issuemaster** [comment]
@deniseyu Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/bosh-io-release-resource&pullRequestId=11)!

**Review by vito — CHANGES_REQUESTED** [review]
Thanks for submitting this! One request though: inferring it from the repository name doesn't feel very clean to me, as it's pretty often that the repo name doesn't actually match the release name. Often, they'll have a `-release` or `-boshrelease` suffix.

The name is available in the tarball itself; within the tarball there's a `release.MF` file, which is a YAML file with a `name` key. For example, here's the one for `diego-release`:

```
---
packages:
- name: auctioneer
  version: 4e190e2393672649968a4fb63825be61b86c5b3d
  fingerprint: 4e190e2393672649968a4fb63825be61b86c5b3d
  sha1: 121ef61fa7777cdaf711946781bb1ff47ea737e2
  dependencies:
  - golang
# snipped the rest
license:
  version: e5665430b5aafd47589f9df4e2345684d3924831
  fingerprint: e5665430b5aafd47589f9df4e2345684d3924831
  sha1: 3dbb1fe81392fb1ff3a58cbaa3f7e05b6980e6b3
commit_hash: a891ebef
uncommitted_changes: false
name: diego
version: 1.14.0
```

Parsing YAML with bash sounds un-fun but maybe it could just grep for `name:` and take the last word?

The `release.MF` file can be extracted on its own via `tar zxf <file>.tgz -- release.MF`, to avoid extracting everything.

Also willing to be swayed the other way here, if the existing behavior seems more intuitive to you.

**Comment by jtarchie** [comment]
We are considering this pull request dead due to inactivity. Please feel free to reopen a new pull request with the requested changes. Thanks!

**Pull request closed without merging**
